frase = str(input('Escreva uma Frase: '))
frase = frase.upper()
print("A Frase: {}".format(frase))
print('Quantidade de Vezes em que \'A\' aparece: {}'.format(frase.count('A')))
print('Posição em que \'A\' aparece pela primeira vez: {}'.format(frase.find('A')))
print('Posição em que \'A\' aparece pela ultima vez: {}'.format(frase.rfind('A')))
