str = input('Digite Algo: ')
print('O Tipo Primitivo desse valor é {}'.format(type(str)))
print('Só tem Espaços ? {}'.format(str.isspace()))
print('É um número? {}'.format(str.isnumeric()))
print('É Alfabético? {}'.format(str.isalpha()))
print('É Alfanumérico? {}'.format(str.isalnum()))
print('Está em maiúsculas? {}'.format(str.isupper()))
print('Está em minúsculas? {}'.format(str.islower()))
print('Está capitalizada? {}'.format(str.istitle()))